/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package vwcVISUAL;

/**
 *
 * @author KELVIN
 */
public class Play extends javax.swing.JFrame {

    /**
     * Creates new form Play
     */
    public Play() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(jButton1);
        jButton1.setBounds(210, 10, 90, 70);
        getContentPane().add(jButton2);
        jButton2.setBounds(10, 10, 90, 70);
        getContentPane().add(jButton3);
        jButton3.setBounds(110, 10, 90, 70);
        getContentPane().add(jButton4);
        jButton4.setBounds(510, 10, 90, 70);
        getContentPane().add(jButton5);
        jButton5.setBounds(310, 10, 90, 70);
        getContentPane().add(jButton6);
        jButton6.setBounds(410, 10, 90, 70);
        getContentPane().add(jButton7);
        jButton7.setBounds(210, 90, 90, 70);
        getContentPane().add(jButton8);
        jButton8.setBounds(10, 90, 90, 70);
        getContentPane().add(jButton9);
        jButton9.setBounds(110, 90, 90, 70);
        getContentPane().add(jButton10);
        jButton10.setBounds(510, 90, 90, 70);
        getContentPane().add(jButton11);
        jButton11.setBounds(310, 90, 90, 70);
        getContentPane().add(jButton12);
        jButton12.setBounds(410, 90, 90, 70);
        getContentPane().add(jButton13);
        jButton13.setBounds(210, 170, 90, 70);
        getContentPane().add(jButton14);
        jButton14.setBounds(10, 170, 90, 70);
        getContentPane().add(jButton15);
        jButton15.setBounds(110, 170, 90, 70);
        getContentPane().add(jButton16);
        jButton16.setBounds(510, 170, 90, 70);
        getContentPane().add(jButton17);
        jButton17.setBounds(310, 170, 90, 70);
        getContentPane().add(jButton18);
        jButton18.setBounds(410, 170, 90, 70);
        getContentPane().add(jButton19);
        jButton19.setBounds(210, 250, 90, 70);
        getContentPane().add(jButton20);
        jButton20.setBounds(10, 250, 90, 70);
        getContentPane().add(jButton21);
        jButton21.setBounds(110, 250, 90, 70);
        getContentPane().add(jButton22);
        jButton22.setBounds(510, 250, 90, 70);
        getContentPane().add(jButton23);
        jButton23.setBounds(310, 250, 90, 70);
        getContentPane().add(jButton24);
        jButton24.setBounds(410, 250, 90, 70);
        getContentPane().add(jButton25);
        jButton25.setBounds(210, 330, 90, 70);
        getContentPane().add(jButton26);
        jButton26.setBounds(10, 330, 90, 70);
        getContentPane().add(jButton27);
        jButton27.setBounds(110, 330, 90, 70);
        getContentPane().add(jButton28);
        jButton28.setBounds(510, 330, 90, 70);
        getContentPane().add(jButton29);
        jButton29.setBounds(310, 330, 90, 70);
        getContentPane().add(jButton30);
        jButton30.setBounds(410, 330, 90, 70);
        getContentPane().add(jButton31);
        jButton31.setBounds(210, 410, 90, 70);
        getContentPane().add(jButton32);
        jButton32.setBounds(10, 410, 90, 70);
        getContentPane().add(jButton33);
        jButton33.setBounds(110, 410, 90, 70);
        getContentPane().add(jButton34);
        jButton34.setBounds(510, 410, 90, 70);
        getContentPane().add(jButton35);
        jButton35.setBounds(310, 410, 90, 70);
        getContentPane().add(jButton36);
        jButton36.setBounds(410, 410, 90, 70);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Play.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Play.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Play.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Play.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Play().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    // End of variables declaration//GEN-END:variables
}
